app/models.py
class Source:
    '''
    Source class to define Source Objects
    '''
    def __init__(self,id,name,description,url,category,language,country):
        self.id = id
        self.name = name
        self.description = description
        self.url = url
        self.category = category
        self.language = language
        self.country = country

class Top_headlines:
    '''
    Top_headlines class to define Top_headlines Objects
    '''
    def __init__(self,source,author,title,description,url,urlToImage,publishedAt,content):
        self.source = source
        self.author = author
        self.title = title
        self.description = description
        self.url = url
        self.urlToImage= urlToImage
        self.publishedAt = publishedAt
        self.content=content

class Article:
    '''
    Article class to define Article Objects
    '''
    def __init__(self,source,author,title,description,url,urlToImage,publishedAt,content):
        self.source = source
        self.author = author
        self.title = title
        self.description = description
        self.url = url
        self.urlToImage= urlToImage
        self.publishedAt = publishedAt
        self.content=content

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options

# Iniializing Flask Extensions
bootstrap = Bootstrap()
def create_app(config_name):
    # Initializing application
    app = Flask(__name__)

    # Setting up configuration
    app.config.from_object(config_options[config_name])

    # app.config.from_pyfile('config.py')
    app.config.update(
        DEBUG = True,
        WTF_CSRF_ENABLED = True,
        SECRET_KEY ='0add1611ecf8610320a09ff4b0e34e42'  
    )
    
     # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Initializing flask extensions
    bootstrap.init_app(app)

    # setting config
    from .request import configure_request
    configure_request(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from flask import render_template,request,redirect,url_for,flash
from . import main
from ..request import get_sources,get_headlines,search_source
from .form import RegistrationForm,LoginForm
from ..models import Source,Top_headlines,Article

# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''
    #getting the general sources
    general_source=get_sources('general')
    health=get_sources('health')
    entertainment=get_sources('entertainment')
    sport=get_sources('sports')
    technology=get_sources('technology')
    title='Top Headlines'
    search_source=request.args.get('source_query')

    if search_source:
        return redirect(url_for('search',source_name=search_source))

    else:
        return render_template('index.html',title=title,general=general_source,health=health,entertainment=entertainment,sport=sport,technology=technology)
@main.route('/articles/<id>')
def Headlines(id):

    '''
    View content page function that returns the news content page and its data
    '''
    headlines_articles=get_headlines(id)
    source=id
    
    return render_template('headlines.html',articles=headlines_articles,source=source)    


@main.route('/search/<source_name>')
def search(source_name):
    '''
    View function to display the search results
    '''
    source_name_list=source_name.split(' ')
    source_name_format='-'.join(source_name_list)
    searched_sources=search_source(source_name_format)
    title=f'search results for {source_name}'
    return render_template('search.html',sources=searched_sources ,title=title)

@main.route('/register',methods=['GET','POST']) 
def register() :
    form=RegistrationForm()
    if form.validate_on_submit():
        flash(f'Account created for {form.username.data}!'),'success'
        return redirect(url_for('index'))
    return render_template('register.html',title='Register',form=form)

@main.route('/login') 
def login() :
    form=LoginForm()
    return render_template('login.html',title='login',form=form)

app/templates/base.html
<html>
    <head>
      
    
        <meta charset="utf-8">
        {% if title %}
        <title> {{ title }}</title>
        {% else %}
        <title> Worldwide News </title>
        
        {% endif %}
        
    </head>

    <body>
        {% extends 'bootstrap/base.html'%}

        {%block styles %}

            {{super() }}
            <!-- Importing the simple mde css and js files   -->
        

        {% endblock %}  

        <!-- Navbar block  --> 
            {% block navbar %}

                {% include 'navbar.html' %}
                
            {% endblock %}
          <!-- Content block -->

        {% block content %}

        {% endblock%} 
        
        
        
    </body>
</html>    

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/headlines.html
 
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
{% endblock %}

{% block content %}

    <div class="container-fluid" id="allsources">
        <div class="overlay">
            {{ macro.display_Source_articles(articles)}}
        </div>
        
    </div>
    
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
{% block content %} 

    
    
    
    <div class="container">

        {% with messages = get_flashed_messages(with_categories=true)%}
        {% if messages%}
           {% for category,message in massages%}
            <div class="alert alert-{{category}}">
                  {{message}}
            </div>
            {%endfor%}
             {% endif %}
          {%endwith%}
        <form class="form">
            <input type="text" name="source_query" placeholder="Search for a source" class="form-control">
            <input type="submit"  value="Submit" class="btn btn-default">
        </form>
       <div class="text-center">
             <h2 class='text-center font-weight-bold headers'>WorldWide News Sources </h2>
       </div>
       <div class="row">
           <div class="col-md-3 gen">
                <h3 class='text-center font-weight-bold headers'>General </h3>
                <hr>
                <ul>
                    {{ macro.displaySourceList(general)}} 
                </ul>
            </div>
            <div class="col-md-3 technology">
                <h3 class='text-center font-weight-bold headers'> Technology </h3>
                <hr>
                <ul>
                    {{ macro.displaySourceList(technology)}} 
                </ul>
            </div>
            <div class="col-md-3 entertainment">
                <h3 class='text-center font-weight-bold headers'>Entertainment </h3>
                <hr>
                    <ul>
                        {{ macro.displaySourceList(entertainment)}} 
                    </ul>
            </div>
            
            <div class="col-md-3 sports">
                <h3 class='text-center font-weight-bold headers'>Sports</h3>
                <hr>
                <ul>
                    {{ macro.displaySourceList(sport)}} 
                </ul>
            </div>
        </div>
    </div>

{%endblock%}

app/templates/login.html
{% extends 'base.html'%}
{% block content%}

{%endblock%}

app/templates/macros.html
{% macro displaySourceList(source_list) %}
        
            <div class="card-body">
                {% for source in source_list %}
                <div class="card-content">
                    <div class="card-title">
                        <h4><a href="{{source.url}}">{{ source.name}}</a></h4>  
                    </div>
                    <div class="card-content">
                            <p>{{source.description}}</p>
                    </div>
                    <diV class="">
                        <P><a href="/articles/{{source.id}}">Lastest stories...</a></P>
                    </diV>
                </div>
                
                {% endfor %}
 
                
            </div>
{% endmacro %}

{% macro display_Source_articles(source_articles_list) %}
<div class="container" id="articles">
 {% for article in source_articles_list%}
      <div class="row" >
            <div class="col-sm-4">
                <div class="card info">
                    <img src="{{article.urlToImage}}" alt="{{article.title}}" height="30%" width="80%" class="card-img">
                </div>
            </div>
            <div class="col-sm-8">
                <div class="card info">
                    <h4><strong>{{article.source.name}}</strong></h4>
                    <div class="card-body">
                        <p><em>{{article.description}}</em></p>
                        <p>{{article.content}}</p>
                        <p>posted by:{{article.author}}</p>
                        <div>
                            <p>posted on:{{article.publishedAt[:10]}}</p>
                        </div>
                        

                        <p><a href="{{article.url}}">Read More....</a></p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    
    {% endmacro %}       

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> News Sources</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Top stories</a></li>
                <li><a href="{{url_for('main.register')}}">Sign up</a></li>
        </div>

    </div>
</div>

app/templates/register.html
{% extends 'base.html'%}
{% block content%}
          <div class="content-section">
              <form method="POST" action=""> 
                   <div class="row">
                        <div class="col-md-3"></div>
                        <div class="col-md-6">
                                        <fieldset class="form-group">
                                            <legend class="border-bottom mb-4">Join Today</legend>
                                            <div class="form-group">
                                                {{form.username.label(class="form-control-label")}}
                                                  {% if form.username.error%}
                                                    {{form.username(class='form-control form-control-lg is-invalid')}}
                                                      <div class="invalid-feedback">
                                                          {%for error in form.username.errors%}
                                                           <span>{{error}}</span>
                                                          {%endfor%}
                                                      </div>
                                                      {%else%}
                                                      {{form.username(class="form-control form-lg")}}
                                                    {%endif%}
                                            </div> 
                                            <div class="form-group">
                                                {{form.email.label(class="form-control-label")}}
                                                {% if form.email.error%}
                                                    {{form.email(class='form-control form-control-lg is-invalid')}}
                                                      <div class="invalid-feedback">
                                                          {%for error in form.email.errors%}
                                                           <span>{{error}}</span>
                                                          {%endfor%}
                                                      </div>
                                                      {%else%}
                                                      {{form.email(class="form-control form-lg")}}
                                                {%endif%}
                                                
                                            </div> 
                                            <div class="form-group">
                                                {{form.password.label(class="form-control-label")}}
                                                {% if form.password.error%}
                                                    {{form.password(class='form-control form-control-lg is-invalid')}}
                                                      <div class="invalid-feedback">
                                                          {%for error in form.password.errors%}
                                                           <span>{{error}}</span>
                                                          {%endfor%}
                                                      </div>
                                                      {%else%}
                                                      {{form.password(class="form-control form-lg")}}
                                                    {%endif%}
                                                
                                            </div> 
                                            <div class="form-group">
                                                {{form.confirm_password.label(class="form-control-label")}}
                                                {% if form.confirm_password.error%}
                                                {{form.confirm_password(class='form-control form-control-lg is-invalid')}}
                                                  <div class="invalid-feedback">
                                                      {%for error in form.confirm_password.error%}
                                                       <span>{{error}}</span>
                                                      {%endfor%}
                                                  </div>
                                                  {%else%}
                                                  {{form.confirm_password(class="form-control form-lg")}}
                                                {%endif%}
                                               
                                            <div class="form-group">
                                                {{form.submit(class='btn btn-outline-info')}}
                                            </div>
                                    
                                    
                                        </fieldset>
                    
                                </form>
                    
                            </div>
                            <div class="border-top pt-3">
                                <small class="text-text">
                                    Already Have An account?<a class="ml-2" href="{{url_for('main.login')}}">sign In</a>
                                </small>
                            </div>
                                    </div>
                        <div class="col-md-3"></div>
                   </div>
                   
{%endblock%}

app/templates/search.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}

{% block content %}
    <div class="container">

        <div class="row">

            <h3> Found {{ sources| count }} matches </h3>
            <hr>
            <ul>
                {{ macro.displayMovieList(sources)}}
            </ul>

        </div>

    </div>
{% endblock %}